development:
  adapter: postgresql
  encoding: unicode
  database: pass_rails_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pass_rails_test
  pool: 5
  username: postgres
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: pass_rails_production
  pool: 5
  username: postgres
  password:
